### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by bubbie**

### CODE REVIEW

**Comment by TTtie** [comment]
1000% improved

**Comment by bubbie** [comment]
what's wrong with my improvements

**Comment by TTtie** [comment]
eh.... it's actually just only a loop

**Comment by bubbie** [comment]
it works the same way as tttie bot did, it does the same things, only smoother

**Comment by TTtie** [comment]
HECK OFF

**Comment by bubbie** [comment]
wow rude I'm only trying to make your bot run smoother, no need to tell me to heck off

**Comment by TTtie** [comment]
tell me why over 1k deletions then,

**Comment by bubbie** [comment]
**improvements**

**Comment by bubbie** [comment]
[will this cute corgi I found on reddit change your mind](http://i.imgur.com/9AsqsFj.gifv)

**Comment by TTtie** [comment]
not dumb m8

**Comment by bubbie** [comment]
you clearly are if you fail to see how I'm improving your bot, pff

**Comment by TTtie** [comment]
blocc m8

**Comment by TTtie** [comment]
though people in my discord server see it

**Comment by TTtie** [comment]
[get rekt m8](https://tttie.ga/img/2016-10-27_13-33-34.png)

**Comment by TTtie** [comment]
@bubbie unblocc u

**Comment by TTtie** [comment]
now go try rekt [pyro bot](https://github.com/tttie/pyro-bot)

**Pull request closed without merging**
